[files]
extend-exclude = ["*", "!*/", "!*.md", "!*.mdx"]

[default.extend-words]
# Scientific Software
namd = "namd"
# Apptainer
Apptainer = "Apptainer"

[default.extend-identifiers]
# Technical terms
SerDe = "SerDe"
JsonSerDe = "JsonSerDe"
