name: Harper

on:
  pull_request:
  workflow_dispatch:

jobs:
  harper:
    name: Grammar and Style Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Harper CLI
        run: cargo install --git https://github.com/Automattic/harper harper-cli --locked

      - name: Show Harper CLI Help
        run: |
          harper-cli --help
          echo "----------------"
          harper-cli lint --help

      - name: Run Harper
        run: |
          find docs src/pages -type f \( -name "*.md" -o -name "*.mdx" \) -print0 | \
          xargs -0 harper-cli lint
